# description: config file for `reads2bwa.smk`
# author: panyq357
# date: 2023-11-06

bwa_index_prefix: ../index/os/rap-db/results/genome/os.rap-db.genome.fa

samples:
  ES:
    R1: ../rawdata/SRR834927_1.fastq.gz
    R2: ../rawdata/SRR834927_2.fastq.gz
  ET:
    R1: ../rawdata/SRR834931_1.fastq.gz
    R2: ../rawdata/SRR834931_2.fastq.gz

threads:  # threads setting for rules
  fastp_pe: 4
  fastp_se: 4
  bwa_mapping_pe: 20
  bwa_mapping_se: 20

