# description: config file for `reads2bwa.smk`
# author: panyq357
# date: 2023-11-06

bwa_index_prefix: /home/panyq/Tools/index-scripts/os/rap-db/results/genome/os.rap-db.genome.fa

samples:
  TT2:
    R1: /mnt/e/LYHLabData/PYQ/TT2/TT2_L1_391.R1.clean.fastq.gz
    R2: /mnt/e/LYHLabData/PYQ/TT2/TT2_L1_391.R2.clean.fastq.gz
  TT23:
    R1: /mnt/e/LYHLabData/PYQ/TT2/TT23_L1_392.R1.clean.fastq.gz
    R2: /mnt/e/LYHLabData/PYQ/TT2/TT23_L1_392.R2.clean.fastq.gz

threads:  # threads setting for rules
  fastp_pe: 4
  fastp_se: 4
  bwa_mapping_pe: 20
  bwa_mapping_se: 20

